- name: Get watchman stat
  stat: path=/usr/local/bin/watchman
  register: watchman

# In 2.0 we can unzip from url
- name: Download watchman
  get_url: url=https://github.com/facebook/watchman/archive/v{{watchman_version}}.zip
    dest=/tmp/watchman-{{watchman_version}}.zip
  when: not watchman.stat.exists

- name: Unzip watchman
  unarchive:
    src=/tmp/watchman-{{watchman_version}}.zip
    dest=/tmp
    creates=/tmp/watchman-{{watchman_version}}
    copy=no
  when: not watchman.stat.exists

- name: Autogen
  shell: ./autogen.sh
    chdir=/tmp/watchman-{{watchman_version}}
  when: not watchman.stat.exists

- name: Configure
  shell: ./configure
    chdir=/tmp/watchman-{{watchman_version}}
  when: not watchman.stat.exists

- name: Make
  shell: make
    chdir=/tmp/watchman-{{watchman_version}}
  when: not watchman.stat.exists

- name: Make Install
  shell: make install
    chdir=/tmp/watchman-{{watchman_version}}
  when: not watchman.stat.exists

- name: Cleanup watchman
  file:
    path={{item}}
    state=absent
  with_items:
    - /tmp/watchman-{{watchman_version}}.zip
    - /tmp/watchman-{{watchman_version}}
