- name: "Get watchman stat"
  stat:
    path: "/usr/local/bin/watchman"
  register: watchman

- name: "Install autoconf if it's missing"
  apt:
    name: "autoconf"

- name: "Unzip watchman"
  unarchive:
    src: "https://github.com/facebook/watchman/archive/master.zip"
    remote_src: yes
    dest: "/tmp"
    creates: "/tmp/watchman-master"
    copy: no
  when: not watchman.stat.exists

- name: "Autogen"
  shell: "./autogen.sh"
  args:
    chdir: "/tmp/watchman-master"
  when: not watchman.stat.exists

- name: "Configure"
  shell: "./configure"
  args:
    chdir: "/tmp/watchman-master"
  when: not watchman.stat.exists

- name: "Make"
  shell: "make"
  args:
    chdir: "/tmp/watchman-master"
  when: not watchman.stat.exists

- name: "Make Install"
  shell: "make install"
  args:
    chdir: "/tmp/watchman-master"
  when: not watchman.stat.exists

- name: "Cleanup watchman"
  file:
    path: "{{item}}"
    state: "absent"
  with_items:
    - "/tmp/master.zip"
    - "/tmp/watchman"
